import { createClient } from '@supabase/supabase-js';
import { createBrowserClient } from '@supabase/ssr';

// Type-safe database types will be generated by Supabase CLI
// For now, using generic types
export type Database = {
  public: {
    Tables: {
      users: any;
      trips: any;
      messages: any;
      cards: any;
      comments: any;
      reminders: any;
      audit_log: any;
      share_links: any;
    };
  };
};

// Client-side Supabase client
export function createClientComponentClient() {
  return createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  );
}

// Service role client (for admin operations)
// Use with caution - bypasses RLS
export function createServiceRoleClient() {
  const hasKey = !!process.env.SUPABASE_SERVICE_ROLE_KEY;
  const hasUrl = !!process.env.NEXT_PUBLIC_SUPABASE_URL;
  console.log('[Supabase] Creating service role client:', { hasKey, hasUrl, url: process.env.NEXT_PUBLIC_SUPABASE_URL?.substring(0, 30) + '...' });

  if (!process.env.SUPABASE_SERVICE_ROLE_KEY) {
    console.error('[Supabase] SUPABASE_SERVICE_ROLE_KEY is NOT set!');
    throw new Error('SUPABASE_SERVICE_ROLE_KEY is not set');
  }

  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY,
    {
      auth: {
        autoRefreshToken: false,
        persistSession: false,
      },
    }
  );
}
