import { NextRequest, NextResponse } from 'next/server';
import type { TravelPlace } from '@/lib/travel/types';

// In-memory cache for places
const placesCache = new Map<string, { places: TravelPlace[]; timestamp: number }>();
const CACHE_TTL = 10 * 60 * 1000; // 10 minutes

// Global place storage by ID (shared with /api/travel/place/details)
declare global {
  var placesById: Map<string, TravelPlace> | undefined;
}

if (!global.placesById) {
  global.placesById = new Map();
}

// Google Places API types (travel-relevant only)
const PLACE_TYPES = [
  'tourist_attraction',
  'museum',
  'art_gallery',
  'park',
  'restaurant',
  'cafe',
  'bar',
  'night_club',
  'spa',
  'lodging',
];

// Types to exclude - non-travel-relevant places
const EXCLUDED_TYPES = new Set([
  // Retail & Home
  'hardware_store', 'home_goods_store', 'furniture_store', 'store',
  'electronics_store', 'department_store', 'convenience_store', 'supermarket',
  'grocery_or_supermarket', 'liquor_store', 'shoe_store', 'clothing_store',
  // Automotive
  'gas_station', 'car_dealer', 'car_rental', 'car_repair', 'car_wash',
  // Services
  'electrician', 'plumber', 'roofing_contractor', 'moving_company',
  'storage', 'laundry', 'locksmith', 'painter', 'general_contractor',
  // Financial & Legal
  'insurance_agency', 'lawyer', 'accounting', 'bank', 'atm', 'finance',
  // Government
  'post_office', 'local_government_office', 'city_hall', 'courthouse', 'embassy',
  // Real Estate
  'real_estate_agency',
  // Health (non-wellness)
  'veterinary_care', 'hospital', 'pharmacy', 'dentist', 'doctor',
  'physiotherapist', 'health',
  // Pets
  'pet_store',
  // Death services
  'cemetery', 'funeral_home',
  // Education
  'school', 'university', 'primary_school', 'secondary_school',
  // Transit (not attractions)
  'transit_station', 'bus_station', 'train_station', 'subway_station',
  'light_rail_station', 'parking', 'taxi_stand',
  // NOTE: Do NOT include 'point_of_interest' or 'establishment' - they're on almost every place
]);

// Check if a place is travel-relevant
function isTravelRelevant(place: { types?: string[] }): boolean {
  const types = place.types || [];

  // Exclude if ANY type is in excluded list
  if (types.some((t: string) => EXCLUDED_TYPES.has(t))) {
    return false;
  }

  return true;
}

// Demo places data for when API key is not available
function getDemoPlaces(cityName: string, lat: number, lng: number): TravelPlace[] {
  const demoData: Record<string, TravelPlace[]> = {
    tokyo: [
      // Hotels
      {
        id: 'tokyo_hotel_park_hyatt',
        name: 'Park Hyatt Tokyo',
        imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
        categories: ['Hotel', 'Luxury', 'Accommodation'],
        rating: 4.8,
        reviewCount: 2543,
        popularityScore: 95,
        description: 'Iconic luxury hotel featured in Lost in Translation, with stunning city views and world-class amenities.',
        shortDescription: 'Luxury hotel in Shinjuku',
        coordinates: { lat: 35.6852, lng: 139.6923 },
        address: '3-7-1-2 Nishi Shinjuku, Shinjuku, Tokyo',
        priceLevel: 4,
        duration: 'Overnight',
        area: 'Shinjuku',
      },
      {
        id: 'tokyo_hotel_aman',
        name: 'Aman Tokyo',
        imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800',
        categories: ['Hotel', 'Luxury', 'Spa'],
        rating: 4.9,
        reviewCount: 1876,
        popularityScore: 92,
        description: 'Serene urban sanctuary combining traditional Japanese aesthetics with modern luxury and exceptional spa.',
        shortDescription: 'Ultra-luxury hotel with spa',
        coordinates: { lat: 35.6751, lng: 139.7634 },
        address: 'Otemachi Tower, Chiyoda, Tokyo',
        priceLevel: 4,
        duration: 'Overnight',
        area: 'Otemachi',
      },
      {
        id: 'tokyo_hotel_shibuya',
        name: 'Shibuya Excel Hotel Tokyu',
        imageUrl: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
        categories: ['Hotel', 'Business', 'Accommodation'],
        rating: 4.4,
        reviewCount: 3421,
        popularityScore: 88,
        description: 'Modern hotel in the heart of Shibuya with views of the famous crossing and excellent location.',
        shortDescription: 'Central Shibuya location',
        coordinates: { lat: 35.6595, lng: 139.7004 },
        address: 'Dogenzaka, Shibuya, Tokyo',
        priceLevel: 3,
        duration: 'Overnight',
        area: 'Shibuya',
      },
      {
        id: 'tokyo_hostel_nui',
        name: 'Nui. Hostel & Bar Lounge',
        imageUrl: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
        categories: ['Hostel', 'Budget', 'Social'],
        rating: 4.6,
        reviewCount: 982,
        popularityScore: 78,
        description: 'Stylish hostel with a vibrant bar and lounge area, perfect for meeting travelers and exploring Tokyo.',
        shortDescription: 'Social hostel in Asakusa',
        coordinates: { lat: 35.7104, lng: 139.7989 },
        address: 'Kuramae, Taito, Tokyo',
        priceLevel: 1,
        duration: 'Overnight',
        area: 'Asakusa',
      },
      {
        id: 'tokyo_hotel_ryokan',
        name: 'Ryokan Sawanoya',
        imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
        categories: ['Inn', 'Traditional', 'Accommodation'],
        rating: 4.7,
        reviewCount: 1234,
        popularityScore: 85,
        description: 'Traditional Japanese inn offering authentic cultural experience with tatami rooms and traditional baths.',
        shortDescription: 'Traditional ryokan',
        coordinates: { lat: 35.7221, lng: 139.7637 },
        address: 'Yanaka, Taito, Tokyo',
        priceLevel: 2,
        duration: 'Overnight',
        area: 'Yanaka',
      },

      // Activities & Landmarks
      {
        id: 'tokyo-tower',
        name: 'Tokyo Tower',
        imageUrl: 'https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=800',
        categories: ['Landmark', 'Views', 'Romantic'],
        rating: 4.6,
        reviewCount: 45000,
        popularityScore: 45000,
        description: 'Iconic red-and-white communications tower offering panoramic city views from observation decks.',
        shortDescription: 'Iconic landmark with city views',
        coordinates: { lat: 35.6586, lng: 139.7454 },
        address: '4 Chome-2-8 Shibakoen, Minato City',
        priceLevel: 2,
        duration: '1-2 hours',
        area: 'Minato',
      },
      {
        id: 'senso-ji',
        name: 'Senso-ji Temple',
        imageUrl: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800',
        categories: ['Temple', 'Historic', 'Culture'],
        rating: 4.7,
        reviewCount: 78000,
        popularityScore: 78000,
        description: 'Ancient Buddhist temple in Asakusa, Tokyo\'s oldest temple dating back to 645 AD.',
        shortDescription: 'Historic Buddhist temple',
        coordinates: { lat: 35.7148, lng: 139.7967 },
        address: '2 Chome-3-1 Asakusa, Taito City',
        priceLevel: 0,
        duration: '1-2 hours',
        area: 'Asakusa',
      },
      {
        id: 'shibuya-crossing',
        name: 'Shibuya Crossing',
        imageUrl: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800',
        categories: ['Landmark', 'Nightlife', 'Urban'],
        rating: 4.5,
        reviewCount: 52000,
        popularityScore: 52000,
        description: 'World-famous pedestrian scramble crossing surrounded by neon lights and giant screens.',
        shortDescription: 'Famous pedestrian crossing',
        coordinates: { lat: 35.6595, lng: 139.7004 },
        address: 'Shibuya, Tokyo',
        priceLevel: 0,
        duration: '30 min',
        area: 'Shibuya',
      },
      {
        id: 'meiji-shrine',
        name: 'Meiji Shrine',
        imageUrl: 'https://images.unsplash.com/photo-1583766395091-2eb9994ed094?w=800',
        categories: ['Shrine', 'Park', 'Peaceful'],
        rating: 4.7,
        reviewCount: 41000,
        popularityScore: 41000,
        description: 'Serene Shinto shrine dedicated to Emperor Meiji, set within a peaceful forest.',
        shortDescription: 'Peaceful Shinto shrine',
        coordinates: { lat: 35.6764, lng: 139.6993 },
        address: '1-1 Yoyogikamizonocho, Shibuya City',
        priceLevel: 0,
        duration: '1-2 hours',
        area: 'Harajuku',
      },
      {
        id: 'akihabara',
        name: 'Akihabara Electric Town',
        imageUrl: 'https://images.unsplash.com/photo-1528164344705-47542687000d?w=800',
        categories: ['Shopping', 'Culture', 'Entertainment'],
        rating: 4.4,
        reviewCount: 35000,
        popularityScore: 35000,
        description: 'Famous electronics and anime district with countless shops, arcades, and maid cafes.',
        shortDescription: 'Electronics and anime district',
        coordinates: { lat: 35.6984, lng: 139.7731 },
        address: 'Akihabara, Chiyoda City',
        priceLevel: 2,
        duration: '2-4 hours',
        area: 'Akihabara',
      },
      {
        id: 'tsukiji-outer',
        name: 'Tsukiji Outer Market',
        imageUrl: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=800',
        categories: ['Food', 'Market', 'Seafood'],
        rating: 4.5,
        reviewCount: 28000,
        popularityScore: 28000,
        description: 'Bustling market with fresh seafood, sushi restaurants, and Japanese street food.',
        shortDescription: 'Famous seafood market',
        coordinates: { lat: 35.6654, lng: 139.7707 },
        address: '4 Chome Tsukiji, Chuo City',
        priceLevel: 2,
        duration: '1-2 hours',
        area: 'Tsukiji',
      },
      {
        id: 'shinjuku-gyoen',
        name: 'Shinjuku Gyoen National Garden',
        imageUrl: 'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800',
        categories: ['Park', 'Garden', 'Nature'],
        rating: 4.6,
        reviewCount: 32000,
        popularityScore: 32000,
        description: 'Beautiful garden featuring Japanese, French, and English landscape designs.',
        shortDescription: 'Beautiful national garden',
        coordinates: { lat: 35.6852, lng: 139.7100 },
        address: '11 Naitomachi, Shinjuku City',
        priceLevel: 1,
        duration: '2-3 hours',
        area: 'Shinjuku',
      },
      {
        id: 'teamlab-planets',
        name: 'teamLab Planets',
        imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800',
        categories: ['Museum', 'Art', 'Interactive'],
        rating: 4.8,
        reviewCount: 25000,
        popularityScore: 25000,
        description: 'Immersive digital art museum where you wade through water and interact with projections.',
        shortDescription: 'Immersive digital art museum',
        coordinates: { lat: 35.6488, lng: 139.7897 },
        address: '6 Chome-1-16 Toyosu, Koto City',
        priceLevel: 3,
        duration: '2 hours',
        area: 'Toyosu',
      },
      {
        id: 'golden-gai',
        name: 'Golden Gai',
        imageUrl: 'https://images.unsplash.com/photo-1554797589-7241bb691973?w=800',
        categories: ['Nightlife', 'Bar', 'Historic'],
        rating: 4.4,
        reviewCount: 18000,
        popularityScore: 18000,
        description: 'Network of narrow alleys with over 200 tiny bars, each seating only a handful of guests.',
        shortDescription: 'Historic alley of tiny bars',
        coordinates: { lat: 35.6938, lng: 139.7036 },
        address: '1 Chome Kabukicho, Shinjuku City',
        priceLevel: 2,
        duration: '2-3 hours',
        area: 'Shinjuku',
      },
      {
        id: 'ueno-park',
        name: 'Ueno Park',
        imageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800',
        categories: ['Park', 'Museum', 'Nature'],
        rating: 4.5,
        reviewCount: 38000,
        popularityScore: 38000,
        description: 'Large public park home to several major museums, temples, and a zoo.',
        shortDescription: 'Large park with museums',
        coordinates: { lat: 35.7146, lng: 139.7732 },
        address: 'Uenokoen, Taito City',
        priceLevel: 0,
        duration: '2-4 hours',
        area: 'Ueno',
      },
      {
        id: 'ginza',
        name: 'Ginza Shopping District',
        imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800',
        categories: ['Shopping', 'Dining', 'Luxury'],
        rating: 4.4,
        reviewCount: 22000,
        popularityScore: 22000,
        description: 'Upscale shopping district with department stores, boutiques, and fine dining.',
        shortDescription: 'Luxury shopping district',
        coordinates: { lat: 35.6717, lng: 139.7649 },
        address: 'Ginza, Chuo City',
        priceLevel: 3,
        duration: '2-4 hours',
        area: 'Ginza',
      },
      {
        id: 'harajuku',
        name: 'Harajuku & Takeshita Street',
        imageUrl: 'https://images.unsplash.com/photo-1532236204992-f5e85c024202?w=800',
        categories: ['Shopping', 'Culture', 'Fashion'],
        rating: 4.3,
        reviewCount: 29000,
        popularityScore: 29000,
        description: 'Youth fashion center known for quirky street style, crepes, and trendy shops.',
        shortDescription: 'Youth fashion district',
        coordinates: { lat: 35.6702, lng: 139.7027 },
        address: 'Jingumae, Shibuya City',
        priceLevel: 2,
        duration: '2-3 hours',
        area: 'Harajuku',
      },
    ],
    paris: [
      // Hotels
      {
        id: 'paris_hotel_ritz',
        name: 'Ritz Paris',
        imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800',
        categories: ['Hotel', 'Luxury', 'Historic'],
        rating: 4.9,
        reviewCount: 3421,
        popularityScore: 98,
        description: 'Legendary palace hotel on Place Vendôme, epitome of Parisian luxury with stunning suites and Michelin-starred dining.',
        shortDescription: 'Iconic luxury hotel',
        coordinates: { lat: 48.8681, lng: 2.3286 },
        address: '15 Place Vendôme, 75001 Paris',
        priceLevel: 4,
        duration: 'Overnight',
        area: 'Place Vendôme',
      },
      {
        id: 'paris_hotel_peninsula',
        name: 'The Peninsula Paris',
        imageUrl: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800',
        categories: ['Hotel', 'Luxury', 'Spa'],
        rating: 4.8,
        reviewCount: 2876,
        popularityScore: 94,
        description: 'Elegant hotel near the Arc de Triomphe with rooftop restaurant, exceptional spa, and classic Parisian style.',
        shortDescription: 'Luxury hotel near Champs-Élysées',
        coordinates: { lat: 48.8738, lng: 2.2950 },
        address: '19 Avenue Kléber, 75116 Paris',
        priceLevel: 4,
        duration: 'Overnight',
        area: 'Champs-Élysées',
      },
      {
        id: 'paris_hotel_marais',
        name: 'Hotel Le Marais',
        imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
        categories: ['Hotel', 'Boutique', 'Accommodation'],
        rating: 4.5,
        reviewCount: 1543,
        popularityScore: 82,
        description: 'Charming boutique hotel in the historic Marais district, perfect location for exploring museums and cafes.',
        shortDescription: 'Boutique hotel in Marais',
        coordinates: { lat: 48.8566, lng: 2.3622 },
        address: 'Le Marais, 75003 Paris',
        priceLevel: 3,
        duration: 'Overnight',
        area: 'Le Marais',
      },
      {
        id: 'paris_hostel_generator',
        name: 'Generator Paris',
        imageUrl: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
        categories: ['Hostel', 'Budget', 'Social'],
        rating: 4.3,
        reviewCount: 2134,
        popularityScore: 76,
        description: 'Modern hostel with vibrant bar and social atmosphere, near Canal Saint-Martin and central attractions.',
        shortDescription: 'Trendy hostel',
        coordinates: { lat: 48.8799, lng: 2.3716 },
        address: 'Place du Colonel Fabien, 75010 Paris',
        priceLevel: 1,
        duration: 'Overnight',
        area: 'Canal Saint-Martin',
      },
      {
        id: 'paris_hotel_montmartre',
        name: 'Terrass Hotel Montmartre',
        imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800',
        categories: ['Hotel', 'Rooftop', 'Accommodation'],
        rating: 4.6,
        reviewCount: 1876,
        popularityScore: 87,
        description: 'Boutique hotel with stunning rooftop terrace overlooking Paris, in the heart of artistic Montmartre.',
        shortDescription: 'Hotel with rooftop views',
        coordinates: { lat: 48.8867, lng: 2.3431 },
        address: '12-14 Rue Joseph de Maistre, 75018 Paris',
        priceLevel: 3,
        duration: 'Overnight',
        area: 'Montmartre',
      },

      // Activities & Landmarks
      {
        id: 'eiffel-tower',
        name: 'Eiffel Tower',
        imageUrl: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce65f4?w=800',
        categories: ['Landmark', 'Views', 'Romantic'],
        rating: 4.7,
        reviewCount: 125000,
        popularityScore: 125000,
        description: 'Iconic iron lattice tower and the most-visited paid monument in the world.',
        shortDescription: 'Iconic Paris landmark',
        coordinates: { lat: 48.8584, lng: 2.2945 },
        address: 'Champ de Mars, 5 Avenue Anatole France',
        priceLevel: 2,
        duration: '2-3 hours',
        area: '7th Arrondissement',
      },
      {
        id: 'louvre',
        name: 'Louvre Museum',
        imageUrl: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800',
        categories: ['Museum', 'Art', 'Historic'],
        rating: 4.8,
        reviewCount: 98000,
        popularityScore: 98000,
        description: 'World\'s largest art museum and home to the Mona Lisa and Venus de Milo.',
        shortDescription: 'World-famous art museum',
        coordinates: { lat: 48.8606, lng: 2.3376 },
        address: 'Rue de Rivoli',
        priceLevel: 2,
        duration: '3-5 hours',
        area: '1st Arrondissement',
      },
      {
        id: 'notre-dame',
        name: 'Notre-Dame Cathedral',
        imageUrl: 'https://images.unsplash.com/photo-1478391679764-b2d8b3cd1e94?w=800',
        categories: ['Cathedral', 'Historic', 'Architecture'],
        rating: 4.7,
        reviewCount: 72000,
        popularityScore: 72000,
        description: 'Medieval Catholic cathedral, masterpiece of French Gothic architecture.',
        shortDescription: 'Gothic cathedral masterpiece',
        coordinates: { lat: 48.8530, lng: 2.3499 },
        address: '6 Parvis Notre-Dame',
        priceLevel: 0,
        duration: '1-2 hours',
        area: 'Île de la Cité',
      },
      {
        id: 'sacre-coeur',
        name: 'Sacré-Cœur Basilica',
        imageUrl: 'https://images.unsplash.com/photo-1550340499-a6c60fc8287c?w=800',
        categories: ['Church', 'Views', 'Historic'],
        rating: 4.6,
        reviewCount: 54000,
        popularityScore: 54000,
        description: 'White-domed basilica atop Montmartre with stunning city views.',
        shortDescription: 'Hilltop basilica with views',
        coordinates: { lat: 48.8867, lng: 2.3431 },
        address: '35 Rue du Chevalier de la Barre',
        priceLevel: 0,
        duration: '1-2 hours',
        area: 'Montmartre',
      },
      {
        id: 'arc-de-triomphe',
        name: 'Arc de Triomphe',
        imageUrl: 'https://images.unsplash.com/photo-1509439581779-6298f75bf6e5?w=800',
        categories: ['Monument', 'Historic', 'Views'],
        rating: 4.6,
        reviewCount: 48000,
        popularityScore: 48000,
        description: 'Iconic triumphal arch honoring those who fought for France.',
        shortDescription: 'Iconic triumphal arch',
        coordinates: { lat: 48.8738, lng: 2.2950 },
        address: 'Place Charles de Gaulle',
        priceLevel: 2,
        duration: '1 hour',
        area: 'Champs-Élysées',
      },
      {
        id: 'musee-dorsay',
        name: 'Musée d\'Orsay',
        imageUrl: 'https://images.unsplash.com/photo-1591981595960-f0f1cdd23e74?w=800',
        categories: ['Museum', 'Art', 'Impressionism'],
        rating: 4.8,
        reviewCount: 62000,
        popularityScore: 62000,
        description: 'Former railway station housing the world\'s largest Impressionist collection.',
        shortDescription: 'Impressionist art museum',
        coordinates: { lat: 48.8600, lng: 2.3266 },
        address: '1 Rue de la Légion d\'Honneur',
        priceLevel: 2,
        duration: '2-4 hours',
        area: '7th Arrondissement',
      },
    ],
    'new york': [
      // Hotels
      {
        id: 'newyork_hotel_plaza',
        name: 'The Plaza Hotel',
        imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
        categories: ['Hotel', 'Luxury', 'Historic'],
        rating: 4.7,
        reviewCount: 4521,
        popularityScore: 96,
        description: 'Legendary luxury hotel overlooking Central Park, featured in countless films and offering timeless elegance.',
        shortDescription: 'Iconic luxury hotel',
        coordinates: { lat: 40.7644, lng: -73.9744 },
        address: 'Fifth Avenue at Central Park South, New York',
        priceLevel: 4,
        duration: 'Overnight',
        area: 'Midtown',
      },
      {
        id: 'newyork_hotel_standard',
        name: 'The Standard, High Line',
        imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800',
        categories: ['Hotel', 'Boutique', 'Modern'],
        rating: 4.5,
        reviewCount: 3124,
        popularityScore: 89,
        description: 'Trendy boutique hotel straddling the High Line with stunning Hudson River views and rooftop bar.',
        shortDescription: 'Trendy hotel on High Line',
        coordinates: { lat: 40.7406, lng: -74.0084 },
        address: '848 Washington St, New York',
        priceLevel: 3,
        duration: 'Overnight',
        area: 'Meatpacking District',
      },
      {
        id: 'newyork_hotel_ace',
        name: 'Ace Hotel New York',
        imageUrl: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
        categories: ['Hotel', 'Accommodation', 'Hip'],
        rating: 4.4,
        reviewCount: 2876,
        popularityScore: 85,
        description: 'Hip hotel in NoMad with artistic design, lively lobby bar, and excellent restaurant.',
        shortDescription: 'Hip NoMad hotel',
        coordinates: { lat: 40.7455, lng: -73.9879 },
        address: '20 W 29th St, New York',
        priceLevel: 3,
        duration: 'Overnight',
        area: 'NoMad',
      },
      {
        id: 'newyork_hostel_jazz',
        name: 'Jazz on the Park Hostel',
        imageUrl: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
        categories: ['Hostel', 'Budget', 'Social'],
        rating: 4.2,
        reviewCount: 1892,
        popularityScore: 74,
        description: 'Vibrant hostel near Central Park with live music, social events, and budget-friendly dorms and private rooms.',
        shortDescription: 'Social hostel near Central Park',
        coordinates: { lat: 40.7919, lng: -73.9575 },
        address: '36 W 106th St, New York',
        priceLevel: 1,
        duration: 'Overnight',
        area: 'Upper West Side',
      },
      {
        id: 'newyork_hotel_brooklyn',
        name: 'The William Vale',
        imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
        categories: ['Hotel', 'Modern', 'Accommodation'],
        rating: 4.6,
        reviewCount: 2145,
        popularityScore: 88,
        description: 'Modern Brooklyn hotel with rooftop pool, stunning Manhattan skyline views, and vibrant dining scene.',
        shortDescription: 'Modern Brooklyn hotel',
        coordinates: { lat: 40.7210, lng: -73.9572 },
        address: '111 N 12th St, Brooklyn, New York',
        priceLevel: 3,
        duration: 'Overnight',
        area: 'Williamsburg',
      },

      // Activities & Landmarks
      {
        id: 'statue-liberty',
        name: 'Statue of Liberty',
        imageUrl: 'https://images.unsplash.com/photo-1485738422979-f5c462d49f74?w=800',
        categories: ['Landmark', 'Historic', 'Monument'],
        rating: 4.7,
        reviewCount: 89000,
        popularityScore: 89000,
        description: 'Iconic copper statue gifted by France, symbol of freedom and democracy.',
        shortDescription: 'Iconic symbol of freedom',
        coordinates: { lat: 40.6892, lng: -74.0445 },
        address: 'Liberty Island',
        priceLevel: 2,
        duration: '3-4 hours',
        area: 'Liberty Island',
      },
      {
        id: 'central-park',
        name: 'Central Park',
        imageUrl: 'https://images.unsplash.com/photo-1568515387631-8b650bbcdb90?w=800',
        categories: ['Park', 'Nature', 'Outdoor'],
        rating: 4.8,
        reviewCount: 142000,
        popularityScore: 142000,
        description: '843-acre urban park with meadows, lakes, and iconic landmarks.',
        shortDescription: 'Iconic urban park',
        coordinates: { lat: 40.7829, lng: -73.9654 },
        address: 'Central Park, Manhattan',
        priceLevel: 0,
        duration: '2-4 hours',
        area: 'Manhattan',
      },
      {
        id: 'empire-state',
        name: 'Empire State Building',
        imageUrl: 'https://images.unsplash.com/photo-1555109307-f7d9da25c244?w=800',
        categories: ['Landmark', 'Views', 'Architecture'],
        rating: 4.7,
        reviewCount: 75000,
        popularityScore: 75000,
        description: '102-story Art Deco skyscraper with observation decks on 86th and 102nd floors.',
        shortDescription: 'Iconic Art Deco skyscraper',
        coordinates: { lat: 40.7484, lng: -73.9857 },
        address: '350 Fifth Avenue',
        priceLevel: 3,
        duration: '1-2 hours',
        area: 'Midtown',
      },
      {
        id: 'times-square',
        name: 'Times Square',
        imageUrl: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800',
        categories: ['Entertainment', 'Shopping', 'Nightlife'],
        rating: 4.5,
        reviewCount: 98000,
        popularityScore: 98000,
        description: 'Iconic commercial intersection known for bright lights and Broadway theaters.',
        shortDescription: 'Iconic bright lights district',
        coordinates: { lat: 40.7580, lng: -73.9855 },
        address: 'Manhattan, NY 10036',
        priceLevel: 2,
        duration: '1-2 hours',
        area: 'Midtown',
      },
      {
        id: 'brooklyn-bridge',
        name: 'Brooklyn Bridge',
        imageUrl: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800',
        categories: ['Landmark', 'Views', 'Historic'],
        rating: 4.8,
        reviewCount: 68000,
        popularityScore: 68000,
        description: 'Historic suspension bridge connecting Manhattan and Brooklyn with stunning views.',
        shortDescription: 'Historic bridge with views',
        coordinates: { lat: 40.7061, lng: -73.9969 },
        address: 'Brooklyn Bridge, New York',
        priceLevel: 0,
        duration: '1 hour',
        area: 'Lower Manhattan',
      },
      {
        id: 'met-museum',
        name: 'The Metropolitan Museum of Art',
        imageUrl: 'https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a?w=800',
        categories: ['Museum', 'Art', 'Culture'],
        rating: 4.8,
        reviewCount: 82000,
        popularityScore: 82000,
        description: 'One of the world\'s largest and finest art museums with 2 million+ works.',
        shortDescription: 'World-class art museum',
        coordinates: { lat: 40.7794, lng: -73.9632 },
        address: '1000 Fifth Avenue',
        priceLevel: 2,
        duration: '3-5 hours',
        area: 'Upper East Side',
      },
    ],
    london: [
      // Hotels
      {
        id: 'london_hotel_savoy',
        name: 'The Savoy',
        imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800',
        categories: ['Hotel', 'Luxury', 'Historic'],
        rating: 4.8,
        reviewCount: 4892,
        popularityScore: 97,
        description: 'Legendary luxury hotel on the Thames, offering timeless elegance, Michelin-starred dining, and impeccable service.',
        shortDescription: 'Iconic luxury hotel',
        coordinates: { lat: 51.5104, lng: -0.1206 },
        address: 'Strand, London WC2R 0EZ',
        priceLevel: 4,
        duration: 'Overnight',
        area: 'Covent Garden',
      },
      {
        id: 'london_hotel_ned',
        name: 'The Ned',
        imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
        categories: ['Hotel', 'Boutique', 'Historic'],
        rating: 4.6,
        reviewCount: 3421,
        popularityScore: 91,
        description: 'Stylish hotel in a 1920s bank building with rooftop bar, multiple restaurants, and members club atmosphere.',
        shortDescription: 'Stylish hotel in historic bank',
        coordinates: { lat: 51.5135, lng: -0.0883 },
        address: '27 Poultry, London EC2R 8AJ',
        priceLevel: 4,
        duration: 'Overnight',
        area: 'City of London',
      },
      {
        id: 'london_hotel_hoxton',
        name: 'The Hoxton, Shoreditch',
        imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800',
        categories: ['Hotel', 'Boutique', 'Accommodation'],
        rating: 4.5,
        reviewCount: 2876,
        popularityScore: 86,
        description: 'Trendy boutique hotel in East London with cozy lobby bar, excellent breakfast, and artistic neighborhood.',
        shortDescription: 'Trendy Shoreditch hotel',
        coordinates: { lat: 51.5255, lng: -0.0809 },
        address: '81 Great Eastern St, London EC2A 3HU',
        priceLevel: 3,
        duration: 'Overnight',
        area: 'Shoreditch',
      },
      {
        id: 'london_hostel_generator',
        name: 'Generator London',
        imageUrl: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
        categories: ['Hostel', 'Budget', 'Social'],
        rating: 4.3,
        reviewCount: 2145,
        popularityScore: 78,
        description: 'Modern hostel near King\'s Cross with bar, cafe, and social events in a vibrant central location.',
        shortDescription: 'Social hostel near King\'s Cross',
        coordinates: { lat: 51.5320, lng: -0.1226 },
        address: '37 Tavistock Pl, London WC1H 9SE',
        priceLevel: 1,
        duration: 'Overnight',
        area: 'King\'s Cross',
      },
      {
        id: 'london_hotel_artist',
        name: 'Artist Residence London',
        imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
        categories: ['Hotel', 'Boutique', 'Accommodation'],
        rating: 4.6,
        reviewCount: 1654,
        popularityScore: 84,
        description: 'Quirky boutique hotel in Pimlico with individually designed rooms, cozy bar, and neighborhood charm.',
        shortDescription: 'Quirky boutique hotel',
        coordinates: { lat: 51.4894, lng: -0.1424 },
        address: '52 Cambridge St, London SW1V 4QQ',
        priceLevel: 3,
        duration: 'Overnight',
        area: 'Pimlico',
      },

      // Activities & Landmarks
      {
        id: 'big-ben',
        name: 'Big Ben & Houses of Parliament',
        imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800',
        categories: ['Landmark', 'Historic', 'Architecture'],
        rating: 4.7,
        reviewCount: 85000,
        popularityScore: 85000,
        description: 'Iconic clock tower and seat of UK Parliament on the Thames.',
        shortDescription: 'Iconic London clock tower',
        coordinates: { lat: 51.5007, lng: -0.1246 },
        address: 'Westminster, London',
        priceLevel: 0,
        duration: '1 hour',
        area: 'Westminster',
      },
      {
        id: 'tower-of-london',
        name: 'Tower of London',
        imageUrl: 'https://images.unsplash.com/photo-1526129318478-62ed807ebdf9?w=800',
        categories: ['Castle', 'Historic', 'Museum'],
        rating: 4.6,
        reviewCount: 72000,
        popularityScore: 72000,
        description: 'Historic castle and fortress housing the Crown Jewels.',
        shortDescription: 'Historic castle & Crown Jewels',
        coordinates: { lat: 51.5081, lng: -0.0759 },
        address: 'Tower Hill, London EC3N 4AB',
        priceLevel: 3,
        duration: '2-3 hours',
        area: 'Tower Hill',
      },
      {
        id: 'british-museum',
        name: 'British Museum',
        imageUrl: 'https://images.unsplash.com/photo-1590168893643-5b7e6d4b0a1c?w=800',
        categories: ['Museum', 'History', 'Culture'],
        rating: 4.8,
        reviewCount: 95000,
        popularityScore: 95000,
        description: 'World-famous museum with artifacts from ancient civilizations.',
        shortDescription: 'World-class museum',
        coordinates: { lat: 51.5194, lng: -0.1270 },
        address: 'Great Russell St, London',
        priceLevel: 0,
        duration: '3-4 hours',
        area: 'Bloomsbury',
      },
      {
        id: 'buckingham-palace',
        name: 'Buckingham Palace',
        imageUrl: 'https://images.unsplash.com/photo-1587298325283-01a8f2b7c7fc?w=800',
        categories: ['Palace', 'Royal', 'Historic'],
        rating: 4.5,
        reviewCount: 68000,
        popularityScore: 68000,
        description: 'Official residence of the British monarch and Changing of the Guard.',
        shortDescription: 'Royal residence',
        coordinates: { lat: 51.5014, lng: -0.1419 },
        address: 'Westminster, London SW1A 1AA',
        priceLevel: 2,
        duration: '1-2 hours',
        area: 'Westminster',
      },
      {
        id: 'london-eye',
        name: 'London Eye',
        imageUrl: 'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=800',
        categories: ['Views', 'Attraction', 'Romantic'],
        rating: 4.5,
        reviewCount: 78000,
        popularityScore: 78000,
        description: 'Giant observation wheel offering panoramic views of London.',
        shortDescription: 'Iconic observation wheel',
        coordinates: { lat: 51.5033, lng: -0.1196 },
        address: 'Riverside Building, London SE1 7PB',
        priceLevel: 3,
        duration: '1 hour',
        area: 'South Bank',
      },
      {
        id: 'borough-market',
        name: 'Borough Market',
        imageUrl: 'https://images.unsplash.com/photo-1547496502-affa22d38842?w=800',
        categories: ['Food', 'Market', 'Local'],
        rating: 4.6,
        reviewCount: 42000,
        popularityScore: 42000,
        description: 'Historic food market with gourmet produce and street food.',
        shortDescription: 'Famous food market',
        coordinates: { lat: 51.5055, lng: -0.0910 },
        address: '8 Southwark St, London SE1 1TL',
        priceLevel: 2,
        duration: '1-2 hours',
        area: 'Southwark',
      },
    ],
    barcelona: [
      // Hotels
      {
        id: 'barcelona_hotel_arts',
        name: 'Hotel Arts Barcelona',
        imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
        categories: ['Hotel', 'Luxury', 'Beachfront'],
        rating: 4.7,
        reviewCount: 3892,
        popularityScore: 95,
        description: 'Iconic beachfront luxury hotel with Michelin-starred dining, stunning Mediterranean views, and world-class spa.',
        shortDescription: 'Luxury beachfront hotel',
        coordinates: { lat: 41.3905, lng: 2.1965 },
        address: 'Carrer de la Marina, 19-21, Barcelona',
        priceLevel: 4,
        duration: 'Overnight',
        area: 'Port Olímpic',
      },
      {
        id: 'barcelona_hotel_casa_fuster',
        name: 'Casa Fuster',
        imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800',
        categories: ['Hotel', 'Boutique', 'Historic'],
        rating: 4.6,
        reviewCount: 2654,
        popularityScore: 89,
        description: 'Modernist boutique hotel on Passeig de Gràcia with rooftop terrace, jazz club, and elegant Catalan design.',
        shortDescription: 'Modernist boutique hotel',
        coordinates: { lat: 41.3955, lng: 2.1602 },
        address: 'Passeig de Gràcia, 132, Barcelona',
        priceLevel: 4,
        duration: 'Overnight',
        area: 'Gràcia',
      },
      {
        id: 'barcelona_hotel_praktik',
        name: 'Praktik Garden',
        imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800',
        categories: ['Hotel', 'Boutique', 'Accommodation'],
        rating: 4.5,
        reviewCount: 1987,
        popularityScore: 83,
        description: 'Stylish boutique hotel with lush garden terrace, near Sagrada Familia and excellent local restaurants.',
        shortDescription: 'Boutique hotel with garden',
        coordinates: { lat: 41.4018, lng: 2.1694 },
        address: 'Carrer de la Diputació, 325, Barcelona',
        priceLevel: 3,
        duration: 'Overnight',
        area: 'Eixample',
      },
      {
        id: 'barcelona_hostel_kabul',
        name: 'Kabul Party Hostel',
        imageUrl: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
        categories: ['Hostel', 'Budget', 'Social'],
        rating: 4.2,
        reviewCount: 3421,
        popularityScore: 76,
        description: 'Legendary party hostel in Plaça Reial with rooftop terrace, daily events, and vibrant social atmosphere.',
        shortDescription: 'Party hostel in Gothic Quarter',
        coordinates: { lat: 41.3802, lng: 2.1759 },
        address: 'Plaça Reial, 17, Barcelona',
        priceLevel: 1,
        duration: 'Overnight',
        area: 'Gothic Quarter',
      },
      {
        id: 'barcelona_hotel_condes',
        name: 'Hotel Condes de Barcelona',
        imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
        categories: ['Hotel', 'Accommodation', 'Central'],
        rating: 4.5,
        reviewCount: 2234,
        popularityScore: 87,
        description: 'Elegant hotel on Passeig de Gràcia with rooftop pool, perfect location for exploring Gaudí\'s architecture.',
        shortDescription: 'Elegant hotel on Passeig de Gràcia',
        coordinates: { lat: 41.3934, lng: 2.1632 },
        address: 'Passeig de Gràcia, 73-75, Barcelona',
        priceLevel: 3,
        duration: 'Overnight',
        area: 'Eixample',
      },

      // Activities & Landmarks
      {
        id: 'sagrada-familia',
        name: 'La Sagrada Familia',
        imageUrl: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800',
        categories: ['Church', 'Architecture', 'Gaudi'],
        rating: 4.8,
        reviewCount: 145000,
        popularityScore: 145000,
        description: 'Gaudí\'s unfinished masterpiece, an iconic basilica under construction since 1882.',
        shortDescription: 'Gaudí\'s iconic basilica',
        coordinates: { lat: 41.4036, lng: 2.1744 },
        address: 'Carrer de Mallorca, 401',
        priceLevel: 3,
        duration: '2-3 hours',
        area: 'Eixample',
      },
      {
        id: 'park-guell',
        name: 'Park Güell',
        imageUrl: 'https://images.unsplash.com/photo-1511527661048-7fe73d85e9a4?w=800',
        categories: ['Park', 'Architecture', 'Gaudi'],
        rating: 4.6,
        reviewCount: 98000,
        popularityScore: 98000,
        description: 'Whimsical park with Gaudí\'s colorful mosaic works and city views.',
        shortDescription: 'Colorful Gaudí park',
        coordinates: { lat: 41.4145, lng: 2.1527 },
        address: 'Carrer d\'Olot, 5',
        priceLevel: 2,
        duration: '2 hours',
        area: 'Gràcia',
      },
      {
        id: 'la-rambla',
        name: 'La Rambla',
        imageUrl: 'https://images.unsplash.com/photo-1558642084-fd07fae5282e?w=800',
        categories: ['Street', 'Shopping', 'Culture'],
        rating: 4.4,
        reviewCount: 65000,
        popularityScore: 65000,
        description: 'Famous tree-lined pedestrian street with shops, cafes, and street performers.',
        shortDescription: 'Famous pedestrian boulevard',
        coordinates: { lat: 41.3809, lng: 2.1734 },
        address: 'La Rambla, Barcelona',
        priceLevel: 0,
        duration: '1-2 hours',
        area: 'Ciutat Vella',
      },
      {
        id: 'casa-batllo',
        name: 'Casa Batlló',
        imageUrl: 'https://images.unsplash.com/photo-1536152470836-b943b246224c?w=800',
        categories: ['Architecture', 'Gaudi', 'Museum'],
        rating: 4.7,
        reviewCount: 52000,
        popularityScore: 52000,
        description: 'Stunning Gaudí-designed building with dragon-inspired roof.',
        shortDescription: 'Gaudí masterpiece',
        coordinates: { lat: 41.3916, lng: 2.1650 },
        address: 'Passeig de Gràcia, 43',
        priceLevel: 3,
        duration: '1-2 hours',
        area: 'Eixample',
      },
      {
        id: 'barceloneta-beach',
        name: 'Barceloneta Beach',
        imageUrl: 'https://images.unsplash.com/photo-1562883676-8c7feb83f09b?w=800',
        categories: ['Beach', 'Outdoor', 'Relaxation'],
        rating: 4.4,
        reviewCount: 38000,
        popularityScore: 38000,
        description: 'Popular city beach with seafood restaurants and beach bars.',
        shortDescription: 'Popular city beach',
        coordinates: { lat: 41.3784, lng: 2.1925 },
        address: 'Passeig Marítim, Barcelona',
        priceLevel: 0,
        duration: '2-4 hours',
        area: 'Barceloneta',
      },
      {
        id: 'gothic-quarter',
        name: 'Gothic Quarter',
        imageUrl: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800',
        categories: ['Historic', 'Walking', 'Architecture'],
        rating: 4.6,
        reviewCount: 48000,
        popularityScore: 48000,
        description: 'Medieval neighborhood with narrow streets, historic buildings, and cafes.',
        shortDescription: 'Medieval old town',
        coordinates: { lat: 41.3833, lng: 2.1761 },
        address: 'Barri Gòtic, Barcelona',
        priceLevel: 0,
        duration: '2-3 hours',
        area: 'Ciutat Vella',
      },
    ],
    bali: [
      // Hotels
      {
        id: 'bali_resort_mulia',
        name: 'The Mulia Bali',
        imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800',
        categories: ['Resort', 'Luxury', 'Beachfront'],
        rating: 4.8,
        reviewCount: 5234,
        popularityScore: 96,
        description: 'Ultra-luxury beachfront resort in Nusa Dua with stunning infinity pools, world-class spa, and exceptional dining.',
        shortDescription: 'Luxury beachfront resort',
        coordinates: { lat: -8.7982, lng: 115.2297 },
        address: 'Jl. Raya Nusa Dua Selatan, Bali',
        priceLevel: 4,
        duration: 'Overnight',
        area: 'Nusa Dua',
      },
      {
        id: 'bali_resort_hanging_gardens',
        name: 'Hanging Gardens of Bali',
        imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
        categories: ['Resort', 'Luxury', 'Spa'],
        rating: 4.9,
        reviewCount: 3892,
        popularityScore: 94,
        description: 'Iconic jungle resort with world-famous infinity pools overlooking rainforest, voted best hotel pool in the world.',
        shortDescription: 'Jungle resort with infinity pools',
        coordinates: { lat: -8.5392, lng: 115.2915 },
        address: 'Desa Buahan, Payangan, Gianyar, Bali',
        priceLevel: 4,
        duration: 'Overnight',
        area: 'Ubud',
      },
      {
        id: 'bali_hotel_bambu_indah',
        name: 'Bambu Indah',
        imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
        categories: ['Hotel', 'Boutique', 'Eco'],
        rating: 4.6,
        reviewCount: 1987,
        popularityScore: 86,
        description: 'Unique eco-luxury boutique hotel in Ubud with antique Javanese bridal homes, natural pools, and organic farm.',
        shortDescription: 'Eco-luxury boutique hotel',
        coordinates: { lat: -8.5162, lng: 115.2629 },
        address: 'Banjar Baung, Sayan, Ubud, Bali',
        priceLevel: 3,
        duration: 'Overnight',
        area: 'Ubud',
      },
      {
        id: 'bali_hostel_puri_garden',
        name: 'Puri Garden Hotel & Hostel',
        imageUrl: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
        categories: ['Hostel', 'Budget', 'Social'],
        rating: 4.3,
        reviewCount: 2456,
        popularityScore: 78,
        description: 'Budget-friendly hostel in Canggu with pool, social atmosphere, and walking distance to surf beaches.',
        shortDescription: 'Social hostel near beaches',
        coordinates: { lat: -8.6486, lng: 115.1384 },
        address: 'Jl. Pantai Batu Bolong, Canggu, Bali',
        priceLevel: 1,
        duration: 'Overnight',
        area: 'Canggu',
      },
      {
        id: 'bali_resort_alila',
        name: 'Alila Villas Uluwatu',
        imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800',
        categories: ['Resort', 'Luxury', 'Accommodation'],
        rating: 4.8,
        reviewCount: 3124,
        popularityScore: 92,
        description: 'Clifftop luxury villas with contemporary design, spectacular ocean views, and award-winning architecture.',
        shortDescription: 'Clifftop luxury villas',
        coordinates: { lat: -8.8292, lng: 115.0849 },
        address: 'Jl. Belimbing Sari, Pecatu, Bali',
        priceLevel: 4,
        duration: 'Overnight',
        area: 'Uluwatu',
      },

      // Activities & Landmarks
      {
        id: 'ubud-rice-terraces',
        name: 'Tegallalang Rice Terraces',
        imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
        categories: ['Nature', 'Scenic', 'Culture'],
        rating: 4.5,
        reviewCount: 42000,
        popularityScore: 42000,
        description: 'Iconic terraced rice paddies with stunning views and swing activities.',
        shortDescription: 'Iconic rice terraces',
        coordinates: { lat: -8.4312, lng: 115.2779 },
        address: 'Tegallalang, Gianyar',
        priceLevel: 1,
        duration: '2-3 hours',
        area: 'Ubud',
      },
      {
        id: 'tanah-lot',
        name: 'Tanah Lot Temple',
        imageUrl: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=800',
        categories: ['Temple', 'Scenic', 'Sunset'],
        rating: 4.6,
        reviewCount: 58000,
        popularityScore: 58000,
        description: 'Ancient Hindu temple perched on a rock formation in the sea.',
        shortDescription: 'Iconic sea temple',
        coordinates: { lat: -8.6212, lng: 115.0869 },
        address: 'Beraban, Kediri, Tabanan',
        priceLevel: 1,
        duration: '2 hours',
        area: 'Tabanan',
      },
      {
        id: 'ubud-monkey-forest',
        name: 'Sacred Monkey Forest Sanctuary',
        imageUrl: 'https://images.unsplash.com/photo-1544644181-1484b3f0e573?w=800',
        categories: ['Nature', 'Wildlife', 'Temple'],
        rating: 4.5,
        reviewCount: 35000,
        popularityScore: 35000,
        description: 'Lush forest sanctuary home to hundreds of monkeys and ancient temples.',
        shortDescription: 'Monkey sanctuary & temples',
        coordinates: { lat: -8.5185, lng: 115.2588 },
        address: 'Jl. Monkey Forest, Ubud',
        priceLevel: 1,
        duration: '1-2 hours',
        area: 'Ubud',
      },
      {
        id: 'uluwatu-temple',
        name: 'Uluwatu Temple',
        imageUrl: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800',
        categories: ['Temple', 'Cliffside', 'Sunset'],
        rating: 4.7,
        reviewCount: 48000,
        popularityScore: 48000,
        description: 'Cliffside temple offering spectacular sunset views and Kecak dance.',
        shortDescription: 'Cliffside sunset temple',
        coordinates: { lat: -8.8291, lng: 115.0849 },
        address: 'Pecatu, South Kuta',
        priceLevel: 1,
        duration: '2-3 hours',
        area: 'Uluwatu',
      },
      {
        id: 'seminyak-beach',
        name: 'Seminyak Beach',
        imageUrl: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800',
        categories: ['Beach', 'Nightlife', 'Dining'],
        rating: 4.4,
        reviewCount: 28000,
        popularityScore: 28000,
        description: 'Trendy beach area with upscale bars, restaurants, and beach clubs.',
        shortDescription: 'Trendy beach area',
        coordinates: { lat: -8.6914, lng: 115.1563 },
        address: 'Seminyak, Bali',
        priceLevel: 2,
        duration: '3-5 hours',
        area: 'Seminyak',
      },
      {
        id: 'tirta-empul',
        name: 'Tirta Empul Temple',
        imageUrl: 'https://images.unsplash.com/photo-1604665515673-d4e4c0e48c3e?w=800',
        categories: ['Temple', 'Spiritual', 'Culture'],
        rating: 4.6,
        reviewCount: 32000,
        popularityScore: 32000,
        description: 'Sacred water temple where Balinese Hindus go for ritual purification.',
        shortDescription: 'Sacred water temple',
        coordinates: { lat: -8.4154, lng: 115.3150 },
        address: 'Tampaksiring, Gianyar',
        priceLevel: 1,
        duration: '1-2 hours',
        area: 'Tampaksiring',
      },
    ],
  };

  // Try to match city name
  const cityKey = cityName.toLowerCase();
  if (demoData[cityKey]) {
    return demoData[cityKey];
  }

  // Return generic demo data based on coordinates
  return [
    {
      id: `demo-1-${lat}-${lng}`,
      name: 'Historic City Center',
      imageUrl: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800',
      categories: ['Historic', 'Culture', 'Walking'],
      rating: 4.6,
      reviewCount: 15000,
      popularityScore: 15000,
      description: 'Explore the charming historic center with beautiful architecture and local shops.',
      shortDescription: 'Beautiful historic area',
      coordinates: { lat: parseFloat(lat.toString()), lng: parseFloat(lng.toString()) },
      address: 'City Center',
      priceLevel: 0,
      duration: '2-3 hours',
      area: 'Downtown',
    },
    {
      id: `demo-2-${lat}-${lng}`,
      name: 'Central Park',
      imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800',
      categories: ['Park', 'Nature', 'Outdoor'],
      rating: 4.5,
      reviewCount: 12000,
      popularityScore: 12000,
      description: 'A beautiful green space perfect for relaxation, walking, and outdoor activities.',
      shortDescription: 'Popular city park',
      coordinates: { lat: parseFloat(lat.toString()) + 0.01, lng: parseFloat(lng.toString()) + 0.01 },
      address: 'Central Area',
      priceLevel: 0,
      duration: '1-2 hours',
      area: 'Central',
    },
    {
      id: `demo-3-${lat}-${lng}`,
      name: 'Local Food Market',
      imageUrl: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800',
      categories: ['Food', 'Market', 'Local'],
      rating: 4.4,
      reviewCount: 8000,
      popularityScore: 8000,
      description: 'Sample local delicacies and fresh produce at this vibrant market.',
      shortDescription: 'Vibrant local market',
      coordinates: { lat: parseFloat(lat.toString()) - 0.01, lng: parseFloat(lng.toString()) },
      address: 'Market District',
      priceLevel: 1,
      duration: '1-2 hours',
      area: 'Market District',
    },
    {
      id: `demo-4-${lat}-${lng}`,
      name: 'Art Museum',
      imageUrl: 'https://images.unsplash.com/photo-1554907984-15263bfd63bd?w=800',
      categories: ['Museum', 'Art', 'Culture'],
      rating: 4.7,
      reviewCount: 10000,
      popularityScore: 10000,
      description: 'World-class art collection spanning centuries of human creativity.',
      shortDescription: 'Excellent art museum',
      coordinates: { lat: parseFloat(lat.toString()), lng: parseFloat(lng.toString()) - 0.01 },
      address: 'Museum Quarter',
      priceLevel: 2,
      duration: '2-4 hours',
      area: 'Cultural District',
    },
    {
      id: `demo-5-${lat}-${lng}`,
      name: 'Rooftop Bar & Restaurant',
      imageUrl: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800',
      categories: ['Restaurant', 'Bar', 'Views'],
      rating: 4.3,
      reviewCount: 5000,
      popularityScore: 5000,
      description: 'Enjoy cocktails and cuisine with stunning panoramic city views.',
      shortDescription: 'Rooftop dining experience',
      coordinates: { lat: parseFloat(lat.toString()) + 0.005, lng: parseFloat(lng.toString()) - 0.005 },
      address: 'Downtown',
      priceLevel: 3,
      duration: '2-3 hours',
      area: 'Entertainment District',
    },
    {
      id: `demo-6-${lat}-${lng}`,
      name: 'Waterfront Promenade',
      imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
      categories: ['Scenic', 'Walking', 'Romantic'],
      rating: 4.4,
      reviewCount: 7000,
      popularityScore: 7000,
      description: 'Beautiful waterfront walk with cafes, street performers, and lovely views.',
      shortDescription: 'Scenic waterfront area',
      coordinates: { lat: parseFloat(lat.toString()) - 0.005, lng: parseFloat(lng.toString()) + 0.005 },
      address: 'Waterfront',
      priceLevel: 0,
      duration: '1-2 hours',
      area: 'Waterfront',
    },
  ];
}

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const lat = searchParams.get('lat');
  const lng = searchParams.get('lng');
  const radius = searchParams.get('radius') || '10000';
  const city = searchParams.get('city') || '';

  if (!lat || !lng) {
    return NextResponse.json(
      { error: 'lat and lng are required' },
      { status: 400 }
    );
  }

  const cacheKey = `${lat},${lng},${radius},${city}`;

  // Check cache
  const cached = placesCache.get(cacheKey);
  if (cached && Date.now() - cached.timestamp < CACHE_TTL) {
    // Store in global storage for detail page access
    cached.places.forEach(place => global.placesById?.set(place.id, place));
    return NextResponse.json({ places: cached.places, cached: true });
  }

  const apiKey = process.env.GOOGLE_PLACES_API_KEY;

  // If no API key, return demo data
  if (!apiKey) {
    console.log('No Google Places API key - using demo data');
    const demoPlaces = getDemoPlaces(city, parseFloat(lat), parseFloat(lng));
    placesCache.set(cacheKey, { places: demoPlaces, timestamp: Date.now() });
    // Store in global storage for detail page access
    demoPlaces.forEach(place => global.placesById?.set(place.id, place));
    return NextResponse.json({ places: demoPlaces, demo: true });
  }

  try {
    const allPlaces: TravelPlace[] = [];
    const seenIds = new Set<string>();

    // Fetch places for each type
    for (const type of PLACE_TYPES.slice(0, 5)) { // Limit to first 5 types for performance
      const url = new URL('https://maps.googleapis.com/maps/api/place/nearbysearch/json');
      url.searchParams.set('location', `${lat},${lng}`);
      url.searchParams.set('radius', radius);
      url.searchParams.set('type', type);
      url.searchParams.set('key', apiKey);

      const response = await fetch(url.toString());
      if (!response.ok) continue;

      const data = await response.json();
      if (data.status !== 'OK' || !data.results) continue;

      for (const place of data.results) {
        if (seenIds.has(place.place_id)) continue;
        seenIds.add(place.place_id);

        // Get photo URL if available
        let imageUrl = '/placeholder-place.jpg';
        if (place.photos?.[0]?.photo_reference) {
          imageUrl = `https://maps.googleapis.com/maps/api/place/photo?maxwidth=400&photo_reference=${place.photos[0].photo_reference}&key=${apiKey}`;
        }

        // Extract categories from types
        const categories = (place.types || [])
          .filter((t: string) => !['point_of_interest', 'establishment'].includes(t))
          .slice(0, 3)
          .map((t: string) => t.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '));

        // Store raw types for filtering
        const rawTypes = place.types || [];

        const travelPlace: TravelPlace & { _rawTypes?: string[] } = {
          id: place.place_id,
          name: place.name,
          imageUrl,
          categories,
          rating: place.rating || 0,
          reviewCount: place.user_ratings_total || 0,
          popularityScore: place.user_ratings_total || 0,
          description: place.vicinity || '',
          shortDescription: place.vicinity || '',
          coordinates: {
            lat: place.geometry.location.lat,
            lng: place.geometry.location.lng,
          },
          address: place.vicinity,
          priceLevel: place.price_level,
          openNow: place.opening_hours?.open_now,
          area: extractArea(place.vicinity),
        };

        // Add raw types for filtering (will be removed before response)
        (travelPlace as any)._rawTypes = rawTypes;

        allPlaces.push(travelPlace);
      }
    }

    // Filter out non-travel-relevant places (like Home Depot, gas stations, etc.)
    const filteredPlaces = allPlaces
      .filter(place => {
        // Check raw types from API - stored during processing
        const rawTypes = (place as any)._rawTypes || place.categories.map(c => c.toLowerCase().replace(/ /g, '_'));
        return isTravelRelevant({ types: rawTypes });
      })
      .map(place => {
        // Remove internal _rawTypes property before returning
        const { _rawTypes, ...cleanPlace } = place as any;
        return cleanPlace as TravelPlace;
      });

    // Sort by popularity
    filteredPlaces.sort((a, b) => b.popularityScore - a.popularityScore);

    // Cache results
    placesCache.set(cacheKey, { places: filteredPlaces, timestamp: Date.now() });

    // Store in global storage for detail page access
    filteredPlaces.forEach(place => global.placesById?.set(place.id, place));

    return NextResponse.json({ places: filteredPlaces });
  } catch (error) {
    console.error('Failed to fetch places:', error);
    return NextResponse.json(
      { error: 'Failed to fetch places' },
      { status: 500 }
    );
  }
}

function extractArea(vicinity?: string): string {
  if (!vicinity) return '';
  const parts = vicinity.split(',');
  return parts[parts.length - 1]?.trim() || parts[0] || '';
}
